Feature implementation
AdedayoOpeyemi/private-events pull request #1
Opened 2020-07-23 23:04 UTC by aldemeery

### Added

- Authentication.
- Create events.
- View user events.
- View all events.
- Attend/Unattend events.
- Separate attended from unattended events.
- Separate upcoming from past events.

2020-07-24 10:09 UTC, stratospherique requested changes
### Impressive work @team :clap: :clap: However, some requirements need to be implemented in order to get approval for this project. Check :arrow_down: 

#### Views & Helpers

* [x] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [x] There shoud be absolutely NO logic in views.

#### Tests

* [x] models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [x] authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [x] event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
#### General
- **[REQUIRED]** Only used routes should be defined
- **[REQUIRED]** Readme file is descriptive
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-07-27 22:48 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,
Thank you for applying the changes.
However, there are still changes to apply before moving forward

:point_right: There shoud be absolutely NO logic in views.

:point_right: Use the [shoulda_matcher](https://github.com/thoughtbot/shoulda-matchers) gem for **unit testing**

:+1:  **Really Good Job** with integrations tests.

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

2020-07-27 22:48 UTC, maelfosso commented on app/views/users/show.html.erb
> +<% end %>
That is what we called **logic in views**
Use `views helpers` instead of that.

2020-07-27 22:48 UTC, maelfosso commented on app/views/events/index.html.erb
> +<% end %>
Use **views helpers** for that

2020-07-28 17:25 UTC, maelfosso approved these changes
# Congratulations :clap: 

Thank you for applying the suggested changes.
You can merge it :+1: 

Good continuation :handshake: 

Mael FOSSO

2020-07-31 22:37 UTC, merged